language: python
python:
  - "3.8"

dist: xenial
sudo: required

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.8

services:
  - redis-server

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    on_success: never
    on_failure: never